- name: Wait for system (SSH) to become reachable
  wait_for_connection:

- name: Disallow Root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="{{ item.regexp }}" line="{{ item.line }}" backup=yes
  with_items:
    - { regexp: "PermitRootLogin", line: "PermitRootLogin no" }

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Create web root directory
  file: dest="/var/www/{{ domain }}" state=directory owner=ubuntu group=ubuntu mode=0755
