- name: Install php 7.2
  command: amazon-linux-extras install php7.2

- name: configure php.ini
  lineinfile: dest=/etc/php.ini regexp="{{ item.regexp }}" line="{{ item.line }}" backup=yes
  with_items:
    - { regexp: "date.timezone", line: "date.timezone = 'UTC'" }
    - { regexp: "short_open_tag =", line: "short_open_tag = Off" }
    - { regexp: "expose_php =", line: "expose_php = Off" }
    - { regexp: "display_errors =", line: "display_errors = Off" }