- name: Install nginx 1.12
  command: amazon-linux-extras install nginx1.12

- name: Upload default index.php for host
  copy: src=files/index.php dest="/var/www/{{ domain }}" mode=0644

- name: Start Nginx
  service: name=nginx enabled=yes state=started